const CategoryActionTypes = {
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    FETCH_CATEGORY_START: 'FETCH_CATEGORY_START',
    FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE: 'FETCH_CATEGORY_FAILURE'
};

export default CategoryActionTypes;